version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:35"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
