"""Tests for commit_message_validator hook."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from guard.hooks.commit_message_validator import (
    check_ai_emails,
    check_ai_trailers,
    check_generated_footers,
    decide,
    extract_commit_message,
    hook,
)

HOOK_PATH = (
    Path(__file__).resolve().parents[2] / "src" / "guard" / "hooks" / "commit_message_validator.py"
)


class TestAIEmailDetection:
    @pytest.mark.parametrize(
        "email",
        [
            "noreply@anthropic.com",
            "cursoragent@cursor.com",
            "noreply@openai.com",
            "noreply@aider.chat",
            "bot@devin.ai",
            "gemini-code-assist@google.com",
        ],
    )
    def test_known_ai_emails_detected(self, email):
        assert check_ai_emails(f"fix bug\n\nCo-Authored-By: <{email}>") is not None

    def test_copilot_noreply_detected(self):
        msg = "fix bug\n\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
        assert check_ai_emails(msg) is not None

    def test_normal_email_passes(self):
        assert check_ai_emails("fix bug\n\nCo-Authored-By: Dev <dev@company.com>") is None

    def test_anthropic_in_code_context_passes(self):
        assert check_ai_emails("add anthropic SDK dependency") is None


class TestAITrailerDetection:
    @pytest.mark.parametrize(
        ("trailer", "tool"),
        [
            ("Co-Authored-By: Claude", "claude"),
            ("Co-authored-by: Copilot", "copilot"),
            ("Co-Authored-By: Cursor Agent", "cursor"),
            ("Signed-off-by: Codex", "codex"),
            ("Assisted-by: aider (claude-3.5)", "aider"),
            ("Co-Authored-By: Devin", "devin"),
            ("Co-authored-by: Gemini", "gemini"),
            ("Co-Authored-By: ChatGPT", "chatgpt"),
        ],
    )
    def test_trailer_with_ai_tool_detected(self, trailer, tool):
        assert check_ai_trailers(f"fix\n\n{trailer}") is not None, tool

    def test_trailer_with_human_name_passes(self):
        assert check_ai_trailers("fix\n\nCo-Authored-By: Jane Smith <jane@x.com>") is None

    def test_bare_claude_in_message_passes(self):
        assert check_ai_trailers("update claude config") is None

    def test_case_insensitive_trailer(self):
        assert check_ai_trailers("fix\n\nco-authored-by: Claude") is not None


class TestGeneratedFooterDetection:
    @pytest.mark.parametrize(
        "footer",
        [
            "Generated with Claude Code",
            "Generated by Devin",
            "Generated by AI",
            "\U0001f916 Generated with Claude Code",
        ],
    )
    def test_generated_footer_detected(self, footer):
        assert check_generated_footers(f"fix\n\n{footer}") is not None

    def test_generated_in_code_context_passes(self):
        assert check_generated_footers("fix generated file handling") is None


class TestMessageExtraction:
    def test_simple_double_quotes(self):
        assert extract_commit_message('git commit -m "fix bug"') == "fix bug"

    def test_simple_single_quotes(self):
        assert extract_commit_message("git commit -m 'fix bug'") == "fix bug"

    def test_with_a_flag(self):
        assert extract_commit_message('git commit -am "fix bug"') == "fix bug"

    def test_long_flag_equals(self):
        assert extract_commit_message('git commit --message="fix bug"') == "fix bug"

    def test_heredoc_pattern(self):
        cmd = (
            "git commit -m \"$(cat <<'EOF'\nfix bug\n\n"
            'Co-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"\n'
        )
        msg = extract_commit_message(cmd)
        assert msg is not None
        assert "Co-Authored-By" in msg

    def test_not_a_commit_command(self):
        assert extract_commit_message("git status") is None

    def test_commit_without_message_flag(self):
        assert extract_commit_message("git commit --amend") is None

    def test_empty_command(self):
        assert extract_commit_message("") is None


class TestDecideIntegration:
    def test_commit_message_validator_imports(self):
        # Top-level import is the contract.
        assert callable(hook)

    def test_commit_message_validator_allows_safe_input(self):
        assert decide('git commit -m "fix bug"') is None

    def test_commit_message_validator_denies_unsafe_input(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_ai_trailer_denied(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude Opus"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_generated_footer_denied(self):
        result = decide('git commit -m "fix\n\nGenerated with Claude Code"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_non_commit_command_passes(self):
        assert decide("git status") is None


class TestFileBasedMessage:
    def test_file_message_with_ai_attribution_denied(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_clean_passes(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Add feature\n", encoding="utf-8")
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_long_form_flag(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit --file={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_long_form_with_space(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Generated with Claude Code\n", encoding="utf-8")
        result = decide(f"git commit --file {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_short_flag_equals(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_relative_path_resolved_to_cwd(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide("git commit -F msg.txt", cwd=str(tmp_path))
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_missing_file_passes(self):
        assert decide("git commit -F /nonexistent/path/to/msg.txt") is None

    def test_file_message_oversized_file_passes(self, tmp_path):
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text("x" * (200 * 1024), encoding="utf-8")
        # No AI attribution; oversize cap means we skip the file entirely.
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_oversized_with_ai_text_passes(self, tmp_path):
        # Even if a huge file contains AI attribution, the cap protects from
        # regex DoS — we ignore the file rather than scan it. Caller's
        # `git commit` will succeed (or fail) on its own; this hook stays out.
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text(
            "Co-Authored-By: Claude <noreply@anthropic.com>\n" + ("x" * (200 * 1024)),
            encoding="utf-8",
        )
        assert decide(f"git commit -F {msg_file}") is None


def _run_hook(command):
    payload = json.dumps({"tool_name": "Bash", "tool_input": {"command": command}})
    result = subprocess.run(  # noqa: S603 -- explicit interpreter, fixed path
        [sys.executable, str(HOOK_PATH)],
        input=payload,
        capture_output=True,
        text=True,
        check=False,
    )
    out = result.stdout.strip()
    decision = json.loads(out)["hookSpecificOutput"]["permissionDecision"] if out else "passthrough"
    return decision, result.returncode


class TestMultiMessageBypass:
    """B6 — multi-``-m`` and ``-F /dev/stdin`` (and friends) bypasses."""

    def test_multi_dash_m_second_message_caught(self):
        # Footer hidden in the second -m used to escape detection.
        cmd = 'git commit -m "fix" -m "Co-Authored-By: Claude <noreply@anthropic.com>"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_multi_long_message_second_caught(self):
        cmd = 'git commit --message="fix" --message="Co-Authored-By: Claude"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "path",
        [
            "/dev/stdin",
            "/dev/null",
            "/dev/fd/0",
            "/proc/self/fd/0",
        ],
    )
    def test_stream_file_path_denied(self, path):
        result = decide(f"git commit -F {path}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert "stream" in result["hookSpecificOutput"]["permissionDecisionReason"].lower()

    def test_dash_F_short_form(self):  # noqa: N802 -- spec-named
        # ``-F-`` (no space, dash means stdin) — must deny.
        result = decide("git commit -F-")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_long_file_dev_stdin(self):
        result = decide("git commit --file=/dev/stdin")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestSubprocessIntegration:
    def test_clean_commit_passthrough(self):
        decision, code = _run_hook('git commit -m "fix bug"')
        assert decision == "passthrough"
        assert code == 0

    def test_ai_email_denied_exit_2(self):
        decision, code = _run_hook(
            'git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"'
        )
        assert decision == "deny"
        assert code == 2

    def test_generated_footer_denied_exit_2(self):
        decision, code = _run_hook('git commit -m "fix\n\nGenerated with Claude Code"')
        assert decision == "deny"
        assert code == 2

    def test_empty_stdin_passthrough(self):
        result = subprocess.run(  # noqa: S603 -- explicit interpreter, fixed path
            [sys.executable, str(HOOK_PATH)],
            input="",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.stdout.strip() == ""
        assert result.returncode == 0

    def test_malformed_json_denied(self):
        # Tranche 1 hardening I2: malformed JSON now fail-closed denies (rc=2).
        # Renamed from `_passthrough` because the contract has changed.
        result = subprocess.run(  # noqa: S603 -- explicit interpreter, fixed path
            [sys.executable, str(HOOK_PATH)],
            input="NOT JSON",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 2
