# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TracineHQ contributors
"""Tests for commit_message_validator hook."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from guard.hooks.commit_message_validator import (
    check_ai_emails,
    check_ai_trailers,
    check_generated_footers,
    decide,
    extract_commit_message,
    hook,
)

HOOK_PATH = (
    Path(__file__).resolve().parents[2] / "src" / "guard" / "hooks" / "commit_message_validator.py"
)


class TestAIEmailDetection:
    @pytest.mark.parametrize(
        "email",
        [
            "noreply@anthropic.com",
            "cursoragent@cursor.com",
            "noreply@openai.com",
            "noreply@aider.chat",
            "bot@devin.ai",
            "gemini-code-assist@google.com",
        ],
    )
    def test_known_ai_emails_detected(self, email):
        assert check_ai_emails(f"fix bug\n\nCo-Authored-By: <{email}>") is not None

    def test_copilot_noreply_detected(self):
        msg = "fix bug\n\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
        assert check_ai_emails(msg) is not None

    def test_normal_email_passes(self):
        assert check_ai_emails("fix bug\n\nCo-Authored-By: Dev <dev@company.com>") is None

    def test_anthropic_in_code_context_passes(self):
        assert check_ai_emails("add anthropic SDK dependency") is None


class TestAITrailerDetection:
    @pytest.mark.parametrize(
        ("trailer", "tool"),
        [
            ("Co-Authored-By: Claude", "claude"),
            ("Co-authored-by: Copilot", "copilot"),
            ("Co-Authored-By: Cursor Agent", "cursor"),
            ("Signed-off-by: Codex", "codex"),
            ("Assisted-by: aider (claude-3.5)", "aider"),
            ("Co-Authored-By: Devin", "devin"),
            ("Co-authored-by: Gemini", "gemini"),
            ("Co-Authored-By: ChatGPT", "chatgpt"),
        ],
    )
    def test_trailer_with_ai_tool_detected(self, trailer, tool):
        assert check_ai_trailers(f"fix\n\n{trailer}") is not None, tool

    def test_trailer_with_human_name_passes(self):
        assert check_ai_trailers("fix\n\nCo-Authored-By: Jane Smith <jane@x.com>") is None

    def test_bare_claude_in_message_passes(self):
        assert check_ai_trailers("update claude config") is None

    def test_case_insensitive_trailer(self):
        assert check_ai_trailers("fix\n\nco-authored-by: Claude") is not None


class TestGeneratedFooterDetection:
    @pytest.mark.parametrize(
        "footer",
        [
            "Generated with Claude Code",
            "Generated by Devin",
            "Generated by AI",
            "\U0001f916 Generated with Claude Code",
        ],
    )
    def test_generated_footer_detected(self, footer):
        assert check_generated_footers(f"fix\n\n{footer}") is not None

    def test_generated_in_code_context_passes(self):
        assert check_generated_footers("fix generated file handling") is None


class TestMessageExtraction:
    def test_simple_double_quotes(self):
        assert extract_commit_message('git commit -m "fix bug"') == "fix bug"

    def test_simple_single_quotes(self):
        assert extract_commit_message("git commit -m 'fix bug'") == "fix bug"

    def test_with_a_flag(self):
        assert extract_commit_message('git commit -am "fix bug"') == "fix bug"

    def test_long_flag_equals(self):
        assert extract_commit_message('git commit --message="fix bug"') == "fix bug"

    def test_heredoc_pattern(self):
        cmd = (
            "git commit -m \"$(cat <<'EOF'\nfix bug\n\n"
            'Co-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"\n'
        )
        msg = extract_commit_message(cmd)
        assert msg is not None
        assert "Co-Authored-By" in msg

    def test_escaped_double_quotes_in_body_dont_terminate_capture(self):
        # Bypass shape: an escaped \" inside the message body would terminate
        # a naive (.*?)\1 non-greedy match at the first internal quote, hiding
        # any AI-attribution trailer that comes after. The body pattern must
        # skip escaped pairs so the full message is captured.
        cmd = (
            'git commit -m "fix: redeclare plugin.json\\\'s \\"hooks\\" field\n\n'
            'Co-Authored-By: Claude <noreply@anthropic.com>"'
        )
        msg = extract_commit_message(cmd)
        assert msg is not None
        assert "Co-Authored-By" in msg, (
            'escaped-quote bypass: trailer after \\" was dropped by extractor'
        )

    def test_long_flag_with_escaped_quotes_in_body(self):
        # --message form must also survive escaped quotes in the body.
        cmd = (
            'git commit --message="fix: \\"hooks\\" field cleanup\n\n'
            'Co-Authored-By: Claude <noreply@anthropic.com>"'
        )
        msg = extract_commit_message(cmd)
        assert msg is not None
        assert "Co-Authored-By" in msg

    def test_not_a_commit_command(self):
        assert extract_commit_message("git status") is None

    def test_commit_without_message_flag(self):
        assert extract_commit_message("git commit --amend") is None

    def test_empty_command(self):
        assert extract_commit_message("") is None

    def test_no_space_short_m_flag(self):
        # `git commit -m"hello"` is valid shell -- the shell tokenizes
        # `-m"hello"` as a single argv element `-mhello` (or, in POSIX
        # shlex.split semantics, `-mhello` with the quoted segment unescaped).
        # The current regex requires \s+ after -m and misses this entirely.
        # Post-refactor: extraction returns "hello".
        assert extract_commit_message('git commit -m"hello"') == "hello"

    def test_chained_command_before_commit_still_extracts(self):
        # `cd /tmp && git commit -m "fix"` works today via raw-command regex
        # and must still work post-refactor (token walk locates `git commit`
        # within the full token list).
        assert extract_commit_message('cd /tmp && git commit -m "fix"') == "fix"

    def test_semicolon_chained_command_before_commit_still_extracts(self):
        # `cd /tmp ; git commit -m "fix"` -- another chained shape that must
        # continue to work.
        assert extract_commit_message('cd /tmp ; git commit -m "fix"') == "fix"


class TestDecideIntegration:
    def test_commit_message_validator_imports(self):
        # Top-level import is the contract.
        assert callable(hook)

    def test_commit_message_validator_allows_safe_input(self):
        assert decide('git commit -m "fix bug"') is None

    def test_commit_message_validator_denies_unsafe_input(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_ai_trailer_denied(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude Opus"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_generated_footer_denied(self):
        result = decide('git commit -m "fix\n\nGenerated with Claude Code"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_ai_trailer_after_escaped_quotes_in_body_denied(self):
        # Regression: a real failing command had escaped \"hooks\" tokens in
        # the message body BEFORE the Co-Authored-By trailer. The body pattern
        # used to terminate at the first internal \" -- dropping the trailer
        # from the extracted message -- and the hook silently allowed the
        # commit. The fix lets escaped pairs pass through; the trailer must
        # now be visible to check_ai_emails and the decision must be deny.
        cmd = (
            'git commit -m "Fix plugin load failure\n\n'
            'Listing plugin.json\\\'s \\"hooks\\" field triggers a duplicate-load error.\n\n'
            'Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"'
        )
        result = decide(cmd)
        assert result is not None, "escaped-quote bypass slipped past decide()"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert "noreply@anthropic.com" in result["hookSpecificOutput"]["permissionDecisionReason"]

    def test_no_space_short_flag_with_attribution_denied(self):
        # Bypass shape: dropping the space between -m and the opening quote
        # lets the AI-attribution trailer through under the current regex.
        # Post-refactor: extraction returns the body and decide denies.
        cmd = 'git commit -m"Co-Authored-By: Claude <noreply@anthropic.com>"'
        result = decide(cmd)
        assert result is not None, "no-space -m bypass slipped past decide()"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_unbalanced_quotes_denied(self):
        # `git commit -m "Co-Authored-By: ... <noreply@anthropic.com>`
        # (no closing quote) is currently a silent allow -- the regex
        # finds no match, extraction returns None, decide returns None.
        # Post-refactor: shlex.split raises ValueError -> deny with
        # an explicit "unparsable command" reason.
        cmd = 'git commit -m "Co-Authored-By: Claude <noreply@anthropic.com>'
        result = decide(cmd)
        assert result is not None, "unbalanced quotes silently allowed an AI-attributed commit"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_non_commit_command_passes(self):
        assert decide("git status") is None


class TestFileBasedMessage:
    def test_file_message_with_ai_attribution_denied(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_clean_passes(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Add feature\n", encoding="utf-8")
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_long_form_flag(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit --file={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_long_form_with_space(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Generated with Claude Code\n", encoding="utf-8")
        result = decide(f"git commit --file {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_short_flag_equals(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_relative_path_resolved_to_cwd(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide("git commit -F msg.txt", cwd=str(tmp_path))
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_missing_file_passes(self):
        assert decide("git commit -F /nonexistent/path/to/msg.txt") is None

    def test_file_message_oversized_file_passes(self, tmp_path):
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text("x" * (200 * 1024), encoding="utf-8")
        # No AI attribution; oversize cap means we skip the file entirely.
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_oversized_with_ai_text_passes(self, tmp_path):
        # Even if a huge file contains AI attribution, the cap protects from
        # regex DoS — we ignore the file rather than scan it. Caller's
        # `git commit` will succeed (or fail) on its own; this hook stays out.
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text(
            "Co-Authored-By: Claude <noreply@anthropic.com>\n" + ("x" * (200 * 1024)),
            encoding="utf-8",
        )
        assert decide(f"git commit -F {msg_file}") is None


def _run_hook(command):
    from tests._helpers import decision_from_stdout, run_hook

    rc, stdout, _ = run_hook("commit_message_validator", command)
    decision = decision_from_stdout(stdout) or "passthrough"
    return decision, rc


class TestMultiMessageBypass:
    """Multi-``-m`` and ``-F /dev/stdin`` (and friends) bypass shapes."""

    def test_multi_dash_m_second_message_caught(self):
        # Footer hidden in the second -m used to escape detection.
        cmd = 'git commit -m "fix" -m "Co-Authored-By: Claude <noreply@anthropic.com>"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_multi_long_message_second_caught(self):
        cmd = 'git commit --message="fix" --message="Co-Authored-By: Claude"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "path",
        [
            "/dev/stdin",
            "/dev/null",
            "/dev/fd/0",
            "/proc/self/fd/0",
        ],
    )
    def test_stream_file_path_denied(self, path):
        result = decide(f"git commit -F {path}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert "stream" in result["hookSpecificOutput"]["permissionDecisionReason"].lower()

    def test_dash_F_short_form(self):
        # ``-F-`` (no space, dash means stdin) — must deny.
        result = decide("git commit -F-")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_long_file_dev_stdin(self):
        result = decide("git commit --file=/dev/stdin")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestOpaqueMessageSources:
    """Shapes whose message body the hook can't inspect must deny outright."""

    @pytest.mark.parametrize(
        "cmd",
        [
            # ANSI-C quoting
            "git commit -m $'fix\\n\\nCo-Authored-By: Claude'",
            "git commit --message=$'fix\\n\\nCo-Authored-By: Claude'",
            # Variable expansion in the message slot
            'git commit -m "$MSG"',
            "git commit -m '$MSG'",
            "git commit -m ${MSG}",
            "git commit --message $MSG",
            # Process substitution -F <(...)
            "git commit -F <(echo 'Co-Authored-By: Claude')",
            "git commit --file <(printf 'fix\\n\\nCo-Authored-By: Claude')",
            # Command substitution $(...) in the message slot — opaque, the
            # shell expands after the hook runs so attribution can be smuggled.
            "git commit -m \"$(printf %s 'Co-Authored-By: Claude')\"",
            'git commit -m "$(cat /tmp/msg)"',
            "git commit --message=\"$(echo 'Co-Authored-By: Claude')\"",
            "git commit -m $(printf %s fix)",
        ],
    )
    def test_opaque_message_shape_denied(self, cmd):
        result = decide(cmd)
        assert result is not None, f"opaque shape not denied: {cmd!r}"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_literal_message_still_passes(self):
        """Regression: ordinary literal -m must not match the opaque regex."""
        assert decide('git commit -m "fix bug"') is None
        assert decide("git commit -m 'fix bug'") is None
        assert decide('git commit --message="fix bug"') is None

    def test_heredoc_still_extractable(self):
        """The recognised heredoc shape is NOT opaque — body is inspectable."""
        cmd = (
            "git commit -m \"$(cat <<'EOF'\nfix bug\n\n"
            'Co-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"\n'
        )
        result = decide(cmd)
        # Should deny via attribution detector, not via opaque-source reason.
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        reason = result["hookSpecificOutput"]["permissionDecisionReason"]
        assert "AI attribution" in reason


class TestExtendedAttribution:
    """Recently-added attribution shapes (model names, hyphenated 'Generated-by')."""

    @pytest.mark.parametrize(
        "cmd",
        [
            'git commit -m "fix" -m "Co-Authored-By: Sonnet 4"',
            'git commit -m "fix" -m "Co-Authored-By: Opus 4.7"',
            'git commit -m "fix" -m "Co-Authored-By: Haiku 4.5"',
            'git commit -m "fix" -m "Co-Authored-By: Anthropic AI"',
            'git commit -m "fix" -m "Generated-by: Claude"',
            'git commit -m "fix" -m "Generated-with-Claude"',
        ],
    )
    def test_extended_attribution_denied(self, cmd):
        result = decide(cmd)
        assert result is not None, f"attribution not denied: {cmd!r}"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestSubprocessIntegration:
    def test_clean_commit_passthrough(self):
        decision, code = _run_hook('git commit -m "fix bug"')
        assert decision == "passthrough"
        assert code == 0

    def test_ai_email_denied_exit_2(self):
        decision, code = _run_hook(
            'git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"'
        )
        assert decision == "deny"
        assert code == 2

    def test_generated_footer_denied_exit_2(self):
        decision, code = _run_hook('git commit -m "fix\n\nGenerated with Claude Code"')
        assert decision == "deny"
        assert code == 2

    def test_empty_stdin_passthrough(self):
        result = subprocess.run(
            [sys.executable, str(HOOK_PATH)],
            input="",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.stdout.strip() == ""
        assert result.returncode == 0

    def test_malformed_json_denied(self):
        # Malformed JSON fails closed with rc=2 instead of silently passing.
        result = subprocess.run(
            [sys.executable, str(HOOK_PATH)],
            input="NOT JSON",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 2


class TestAIEmailGitConfigPreflight:
    """Pre-flight check: warn (ASK) when git user.email itself looks AI-attributed.

    The decide() function shells out to ``git config user.email`` once per
    commit attempt. If the configured email matches an AI-tool pattern (e.g.
    ``noreply@anthropic.com``), every commit authored under that identity
    will be tagged as AI-authored even if the message body is clean.
    """

    def _make_completed(
        self,
        stdout: str = "",
        returncode: int = 0,
    ) -> subprocess.CompletedProcess:
        return subprocess.CompletedProcess(
            args=["git", "config", "user.email"],
            returncode=returncode,
            stdout=stdout,
            stderr="",
        )

    @pytest.mark.parametrize(
        ("stdout", "returncode", "expected_decision"),
        [
            # AI-attributed addresses → ASK
            ("noreply@anthropic.com\n", 0, "ask"),
            ("223556219+Copilot@users.noreply.github.com\n", 0, "ask"),
            # Benign / failure / empty → no envelope
            ("dev@company.com\n", 0, None),
            ("", 128, None),
            ("\n", 0, None),
        ],
    )
    def test_email_preflight(self, stdout, returncode, expected_decision):
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
            return_value=self._make_completed(stdout=stdout, returncode=returncode),
        ):
            result = decide('git commit -m "fix bug"')
        if expected_decision is None:
            assert result is None
        else:
            assert result is not None
            assert result["hookSpecificOutput"]["permissionDecision"] == expected_decision
            assert "AI-attributed" in result["hookSpecificOutput"]["permissionDecisionReason"]

    def test_subprocess_failure_passes(self):
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
            side_effect=OSError("git not found"),
        ):
            assert decide('git commit -m "fix bug"') is None

    def test_non_commit_command_skips_subprocess(self):
        # The hook entry point only invokes decide() when "git commit" is in
        # the command — a plain status command shouldn't shell out at all.
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
        ) as spy:
            hook(
                {
                    "tool_name": "Bash",
                    "tool_input": {"command": "git status"},
                }
            )
        assert not spy.called


class TestReadMessageFileFallback:
    """_read_message_file returns None when Path.resolve() raises.

    Regression net: a permission error or symlink loop during resolve must
    fail closed (decide() returns None / allow), not crash the hook.
    """

    def test_resolve_oserror_returns_none(self, tmp_path):
        from guard.hooks.commit_message_validator import _read_message_file

        target = tmp_path / "msg.txt"
        target.write_text("body")
        with patch.object(Path, "resolve", side_effect=OSError("simulated")):
            assert _read_message_file(str(target), str(tmp_path)) is None

    def test_resolve_valueerror_returns_none(self, tmp_path):
        from guard.hooks.commit_message_validator import _read_message_file

        target = tmp_path / "msg.txt"
        target.write_text("body")
        with patch.object(Path, "resolve", side_effect=ValueError("simulated")):
            assert _read_message_file(str(target), str(tmp_path)) is None


class TestTokenLevelHelpers:
    """Cover the new shlex-based helpers introduced in the refactor."""

    def test_safe_tokenize_returns_tokens_for_valid_command(self):
        from guard.hooks.commit_message_validator import _safe_tokenize

        assert _safe_tokenize('git commit -m "fix"') == ["git", "commit", "-m", "fix"]

    def test_safe_tokenize_returns_none_on_unbalanced_quotes(self):
        from guard.hooks.commit_message_validator import _safe_tokenize

        assert _safe_tokenize('git commit -m "unclosed') is None

    def test_find_git_commit_index_simple(self):
        from guard.hooks.commit_message_validator import _find_git_commit_index

        assert _find_git_commit_index(["git", "commit", "-m", "fix"]) == 1

    def test_find_git_commit_index_chained_command(self):
        from guard.hooks.commit_message_validator import _find_git_commit_index

        toks = ["cd", "/tmp", "&&", "git", "commit", "-m", "fix"]
        assert _find_git_commit_index(toks) == 4

    def test_find_git_commit_index_returns_none_when_absent(self):
        from guard.hooks.commit_message_validator import _find_git_commit_index

        assert _find_git_commit_index(["git", "status"]) is None
        assert _find_git_commit_index([]) is None

    def test_is_heredoc_token_recognises_full_shape(self):
        from guard.hooks.commit_message_validator import _is_heredoc_token

        tok = "$(cat <<'EOF'\nfix bug\n\nbody\nEOF\n)"
        assert _is_heredoc_token(tok) is True

    def test_is_heredoc_token_rejects_var_expansion(self):
        from guard.hooks.commit_message_validator import _is_heredoc_token

        assert _is_heredoc_token("$MSG") is False
        assert _is_heredoc_token("$(printf %s fix)") is False

    def test_is_opaque_token_flags_var_expansion(self):
        from guard.hooks.commit_message_validator import _is_opaque_token

        assert _is_opaque_token("$MSG") is True
        assert _is_opaque_token("${MSG}") is True

    def test_is_opaque_token_flags_command_substitution(self):
        from guard.hooks.commit_message_validator import _is_opaque_token

        assert _is_opaque_token("$(printf %s fix)") is True

    def test_is_opaque_token_excludes_heredoc_shape(self):
        from guard.hooks.commit_message_validator import _is_opaque_token

        tok = "$(cat <<'EOF'\nfix bug\nEOF\n)"
        assert _is_opaque_token(tok) is False

    def test_is_opaque_token_excludes_plain_text(self):
        from guard.hooks.commit_message_validator import _is_opaque_token

        assert _is_opaque_token("regular commit message") is False
        assert _is_opaque_token("MSG") is False  # no leading $

    def test_extract_file_flag_path_chained_command(self):
        from guard.hooks.commit_message_validator import _extract_file_flag_path

        # File-flag extraction must work after a chained command too, since
        # the shared tokenization pipeline handles `cd ... && git commit -F`.
        assert _extract_file_flag_path("cd /tmp && git commit -F /tmp/msg.txt") == "/tmp/msg.txt"

    def test_extract_file_flag_path_unparsable_returns_none(self):
        from guard.hooks.commit_message_validator import _extract_file_flag_path

        # Unparsable command: caller (decide) handles deny separately via
        # the tokenize-once check, so this helper just returns None.
        assert _extract_file_flag_path('git commit -F "unclosed') is None

    def test_extract_all_messages_returns_empty_on_unparsable(self):
        from guard.hooks.commit_message_validator import _extract_all_messages

        # Same contract: unparsable -> empty list; decide handles the deny.
        assert _extract_all_messages('git commit -m "unclosed') == []

    def test_extract_all_messages_returns_empty_when_no_git_commit(self):
        from guard.hooks.commit_message_validator import _extract_all_messages

        # Command must contain literal `git commit` -- a `commit` token alone
        # (e.g. from a different VCS) does not satisfy the early-return gate.
        assert _extract_all_messages("hg commit -m fix") == []


class TestExtractAllMessagesPerformance:
    """``_extract_all_messages`` runs in linear time over the token list.

    Pre-refactor used a regex with ``DOTALL`` + backreferences that could
    backtrack quadratically on adversarial input, so an 8 KiB scan cap
    bounded the worst case. Post-refactor uses ``shlex.split`` (linear) +
    a single forward walk over tokens — no cap needed and no quadratic risk.
    Real commit-message argv stays well under 8 KiB anyway.
    """

    def test_normal_multi_m_extraction(self):
        from guard.hooks.commit_message_validator import _extract_all_messages

        messages = _extract_all_messages('git commit -m "fix bug" -m "see #123"')
        assert messages == ["fix bug", "see #123"]

    @pytest.mark.timeout(30)
    def test_long_input_completes_in_bounded_time(self):
        """Linear-time guarantee. Pre-refactor regex with backreferences could
        backtrack quadratically on alternating quote characters; the shlex +
        token-walk implementation is O(n).

        Generous 30s tripwire is a regression catch, not a speed contract.
        Real contract: every -m extracts (no silent cap drops), verified
        below.
        """
        from guard.hooks.commit_message_validator import _extract_all_messages

        adversarial = "git commit " + ("-m 'x' " * 5000)  # ~35 KiB
        messages = _extract_all_messages(adversarial)
        # All 5000 messages extracted (no cap dropping them).
        assert len(messages) == 5000

    def test_late_message_in_long_command_is_still_extracted(self):
        """No silent truncation: a ``-m`` that appears after several KiB of
        leading content must still be captured. The 8 KiB cap used to drop
        post-cap matches; the token-based extractor walks the whole list."""
        from guard.hooks.commit_message_validator import _extract_all_messages

        prefix = 'git commit -m "early-msg"'
        # Use a real comment-block padding shape rather than a single huge
        # token, so shlex tokenizes meaningfully on the way to the late -m.
        padding = " ".join(["# pad"] * 2000)  # ~10 KiB of separate tokens
        late = ' -m "late-msg"'
        cmd = prefix + " " + padding + late
        messages = _extract_all_messages(cmd)
        assert "early-msg" in messages
        assert "late-msg" in messages, "late -m beyond pre-refactor cap must be extracted"
