# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TracineHQ contributors
"""Tests for commit_message_validator hook."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from guard.hooks.commit_message_validator import (
    check_ai_emails,
    check_ai_trailers,
    check_generated_footers,
    decide,
    extract_commit_message,
    hook,
)

HOOK_PATH = (
    Path(__file__).resolve().parents[2] / "src" / "guard" / "hooks" / "commit_message_validator.py"
)


class TestAIEmailDetection:
    @pytest.mark.parametrize(
        "email",
        [
            "noreply@anthropic.com",
            "cursoragent@cursor.com",
            "noreply@openai.com",
            "noreply@aider.chat",
            "bot@devin.ai",
            "gemini-code-assist@google.com",
        ],
    )
    def test_known_ai_emails_detected(self, email):
        assert check_ai_emails(f"fix bug\n\nCo-Authored-By: <{email}>") is not None

    def test_copilot_noreply_detected(self):
        msg = "fix bug\n\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
        assert check_ai_emails(msg) is not None

    def test_normal_email_passes(self):
        assert check_ai_emails("fix bug\n\nCo-Authored-By: Dev <dev@company.com>") is None

    def test_anthropic_in_code_context_passes(self):
        assert check_ai_emails("add anthropic SDK dependency") is None


class TestAITrailerDetection:
    @pytest.mark.parametrize(
        ("trailer", "tool"),
        [
            ("Co-Authored-By: Claude", "claude"),
            ("Co-authored-by: Copilot", "copilot"),
            ("Co-Authored-By: Cursor Agent", "cursor"),
            ("Signed-off-by: Codex", "codex"),
            ("Assisted-by: aider (claude-3.5)", "aider"),
            ("Co-Authored-By: Devin", "devin"),
            ("Co-authored-by: Gemini", "gemini"),
            ("Co-Authored-By: ChatGPT", "chatgpt"),
        ],
    )
    def test_trailer_with_ai_tool_detected(self, trailer, tool):
        assert check_ai_trailers(f"fix\n\n{trailer}") is not None, tool

    def test_trailer_with_human_name_passes(self):
        assert check_ai_trailers("fix\n\nCo-Authored-By: Jane Smith <jane@x.com>") is None

    def test_bare_claude_in_message_passes(self):
        assert check_ai_trailers("update claude config") is None

    def test_case_insensitive_trailer(self):
        assert check_ai_trailers("fix\n\nco-authored-by: Claude") is not None


class TestGeneratedFooterDetection:
    @pytest.mark.parametrize(
        "footer",
        [
            "Generated with Claude Code",
            "Generated by Devin",
            "Generated by AI",
            "\U0001f916 Generated with Claude Code",
        ],
    )
    def test_generated_footer_detected(self, footer):
        assert check_generated_footers(f"fix\n\n{footer}") is not None

    def test_generated_in_code_context_passes(self):
        assert check_generated_footers("fix generated file handling") is None


class TestMessageExtraction:
    def test_simple_double_quotes(self):
        assert extract_commit_message('git commit -m "fix bug"') == "fix bug"

    def test_simple_single_quotes(self):
        assert extract_commit_message("git commit -m 'fix bug'") == "fix bug"

    def test_with_a_flag(self):
        assert extract_commit_message('git commit -am "fix bug"') == "fix bug"

    def test_long_flag_equals(self):
        assert extract_commit_message('git commit --message="fix bug"') == "fix bug"

    def test_heredoc_pattern(self):
        cmd = (
            "git commit -m \"$(cat <<'EOF'\nfix bug\n\n"
            'Co-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"\n'
        )
        msg = extract_commit_message(cmd)
        assert msg is not None
        assert "Co-Authored-By" in msg

    def test_not_a_commit_command(self):
        assert extract_commit_message("git status") is None

    def test_commit_without_message_flag(self):
        assert extract_commit_message("git commit --amend") is None

    def test_empty_command(self):
        assert extract_commit_message("") is None


class TestDecideIntegration:
    def test_commit_message_validator_imports(self):
        # Top-level import is the contract.
        assert callable(hook)

    def test_commit_message_validator_allows_safe_input(self):
        assert decide('git commit -m "fix bug"') is None

    def test_commit_message_validator_denies_unsafe_input(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_ai_trailer_denied(self):
        result = decide('git commit -m "fix\n\nCo-Authored-By: Claude Opus"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_generated_footer_denied(self):
        result = decide('git commit -m "fix\n\nGenerated with Claude Code"')
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_non_commit_command_passes(self):
        assert decide("git status") is None


class TestFileBasedMessage:
    def test_file_message_with_ai_attribution_denied(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_clean_passes(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Add feature\n", encoding="utf-8")
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_long_form_flag(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit --file={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_long_form_with_space(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Generated with Claude Code\n", encoding="utf-8")
        result = decide(f"git commit --file {msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_short_flag_equals(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide(f"git commit -F={msg_file}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_relative_path_resolved_to_cwd(self, tmp_path):
        msg_file = tmp_path / "msg.txt"
        msg_file.write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n", encoding="utf-8")
        result = decide("git commit -F msg.txt", cwd=str(tmp_path))
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_file_message_missing_file_passes(self):
        assert decide("git commit -F /nonexistent/path/to/msg.txt") is None

    def test_file_message_oversized_file_passes(self, tmp_path):
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text("x" * (200 * 1024), encoding="utf-8")
        # No AI attribution; oversize cap means we skip the file entirely.
        assert decide(f"git commit -F {msg_file}") is None

    def test_file_message_oversized_with_ai_text_passes(self, tmp_path):
        # Even if a huge file contains AI attribution, the cap protects from
        # regex DoS — we ignore the file rather than scan it. Caller's
        # `git commit` will succeed (or fail) on its own; this hook stays out.
        msg_file = tmp_path / "huge.txt"
        msg_file.write_text(
            "Co-Authored-By: Claude <noreply@anthropic.com>\n" + ("x" * (200 * 1024)),
            encoding="utf-8",
        )
        assert decide(f"git commit -F {msg_file}") is None


def _run_hook(command):
    payload = json.dumps({"tool_name": "Bash", "tool_input": {"command": command}})
    result = subprocess.run(
        [sys.executable, str(HOOK_PATH)],
        input=payload,
        capture_output=True,
        text=True,
        check=False,
    )
    out = result.stdout.strip()
    decision = json.loads(out)["hookSpecificOutput"]["permissionDecision"] if out else "passthrough"
    return decision, result.returncode


class TestMultiMessageBypass:
    """Multi-``-m`` and ``-F /dev/stdin`` (and friends) bypass shapes."""

    def test_multi_dash_m_second_message_caught(self):
        # Footer hidden in the second -m used to escape detection.
        cmd = 'git commit -m "fix" -m "Co-Authored-By: Claude <noreply@anthropic.com>"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_multi_long_message_second_caught(self):
        cmd = 'git commit --message="fix" --message="Co-Authored-By: Claude"'
        result = decide(cmd)
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    @pytest.mark.parametrize(
        "path",
        [
            "/dev/stdin",
            "/dev/null",
            "/dev/fd/0",
            "/proc/self/fd/0",
        ],
    )
    def test_stream_file_path_denied(self, path):
        result = decide(f"git commit -F {path}")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert "stream" in result["hookSpecificOutput"]["permissionDecisionReason"].lower()

    def test_dash_F_short_form(self):
        # ``-F-`` (no space, dash means stdin) — must deny.
        result = decide("git commit -F-")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_long_file_dev_stdin(self):
        result = decide("git commit --file=/dev/stdin")
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestOpaqueMessageSources:
    """Shapes whose message body the hook can't inspect must deny outright."""

    @pytest.mark.parametrize(
        "cmd",
        [
            # ANSI-C quoting
            "git commit -m $'fix\\n\\nCo-Authored-By: Claude'",
            "git commit --message=$'fix\\n\\nCo-Authored-By: Claude'",
            # Variable expansion in the message slot
            'git commit -m "$MSG"',
            "git commit -m '$MSG'",
            "git commit -m ${MSG}",
            "git commit --message $MSG",
            # Process substitution -F <(...)
            "git commit -F <(echo 'Co-Authored-By: Claude')",
            "git commit --file <(printf 'fix\\n\\nCo-Authored-By: Claude')",
            # Command substitution $(...) in the message slot — opaque, the
            # shell expands after the hook runs so attribution can be smuggled.
            "git commit -m \"$(printf %s 'Co-Authored-By: Claude')\"",
            'git commit -m "$(cat /tmp/msg)"',
            "git commit --message=\"$(echo 'Co-Authored-By: Claude')\"",
            "git commit -m $(printf %s fix)",
        ],
    )
    def test_opaque_message_shape_denied(self, cmd):
        result = decide(cmd)
        assert result is not None, f"opaque shape not denied: {cmd!r}"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_literal_message_still_passes(self):
        """Regression: ordinary literal -m must not match the opaque regex."""
        assert decide('git commit -m "fix bug"') is None
        assert decide("git commit -m 'fix bug'") is None
        assert decide('git commit --message="fix bug"') is None

    def test_heredoc_still_extractable(self):
        """The recognised heredoc shape is NOT opaque — body is inspectable."""
        cmd = (
            "git commit -m \"$(cat <<'EOF'\nfix bug\n\n"
            'Co-Authored-By: Claude <noreply@anthropic.com>\nEOF\n)"\n'
        )
        result = decide(cmd)
        # Should deny via attribution detector, not via opaque-source reason.
        assert result is not None
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"
        reason = result["hookSpecificOutput"]["permissionDecisionReason"]
        assert "AI attribution" in reason


class TestExtendedAttribution:
    """Recently-added attribution shapes (model names, hyphenated 'Generated-by')."""

    @pytest.mark.parametrize(
        "cmd",
        [
            'git commit -m "fix" -m "Co-Authored-By: Sonnet 4"',
            'git commit -m "fix" -m "Co-Authored-By: Opus 4.7"',
            'git commit -m "fix" -m "Co-Authored-By: Haiku 4.5"',
            'git commit -m "fix" -m "Co-Authored-By: Anthropic AI"',
            'git commit -m "fix" -m "Generated-by: Claude"',
            'git commit -m "fix" -m "Generated-with-Claude"',
        ],
    )
    def test_extended_attribution_denied(self, cmd):
        result = decide(cmd)
        assert result is not None, f"attribution not denied: {cmd!r}"
        assert result["hookSpecificOutput"]["permissionDecision"] == "deny"


class TestSubprocessIntegration:
    def test_clean_commit_passthrough(self):
        decision, code = _run_hook('git commit -m "fix bug"')
        assert decision == "passthrough"
        assert code == 0

    def test_ai_email_denied_exit_2(self):
        decision, code = _run_hook(
            'git commit -m "fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"'
        )
        assert decision == "deny"
        assert code == 2

    def test_generated_footer_denied_exit_2(self):
        decision, code = _run_hook('git commit -m "fix\n\nGenerated with Claude Code"')
        assert decision == "deny"
        assert code == 2

    def test_empty_stdin_passthrough(self):
        result = subprocess.run(
            [sys.executable, str(HOOK_PATH)],
            input="",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.stdout.strip() == ""
        assert result.returncode == 0

    def test_malformed_json_denied(self):
        # Malformed JSON fails closed with rc=2 instead of silently passing.
        result = subprocess.run(
            [sys.executable, str(HOOK_PATH)],
            input="NOT JSON",
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 2


class TestAIEmailGitConfigPreflight:
    """Pre-flight check: warn (ASK) when git user.email itself looks AI-attributed.

    The decide() function shells out to ``git config user.email`` once per
    commit attempt. If the configured email matches an AI-tool pattern (e.g.
    ``noreply@anthropic.com``), every commit authored under that identity
    will be tagged as AI-authored even if the message body is clean.
    """

    def _make_completed(
        self,
        stdout: str = "",
        returncode: int = 0,
    ) -> subprocess.CompletedProcess:
        return subprocess.CompletedProcess(
            args=["git", "config", "user.email"],
            returncode=returncode,
            stdout=stdout,
            stderr="",
        )

    @pytest.mark.parametrize(
        ("stdout", "returncode", "expected_decision"),
        [
            # AI-attributed addresses → ASK
            ("noreply@anthropic.com\n", 0, "ask"),
            ("223556219+Copilot@users.noreply.github.com\n", 0, "ask"),
            # Benign / failure / empty → no envelope
            ("dev@company.com\n", 0, None),
            ("", 128, None),
            ("\n", 0, None),
        ],
    )
    def test_email_preflight(self, stdout, returncode, expected_decision):
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
            return_value=self._make_completed(stdout=stdout, returncode=returncode),
        ):
            result = decide('git commit -m "fix bug"')
        if expected_decision is None:
            assert result is None
        else:
            assert result is not None
            assert result["hookSpecificOutput"]["permissionDecision"] == expected_decision
            assert "AI-attributed" in result["hookSpecificOutput"]["permissionDecisionReason"]

    def test_subprocess_failure_passes(self):
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
            side_effect=OSError("git not found"),
        ):
            assert decide('git commit -m "fix bug"') is None

    def test_non_commit_command_skips_subprocess(self):
        # The hook entry point only invokes decide() when "git commit" is in
        # the command — a plain status command shouldn't shell out at all.
        with patch(
            "guard.hooks.commit_message_validator.subprocess.run",
            autospec=True,
        ) as spy:
            hook(
                {
                    "tool_name": "Bash",
                    "tool_input": {"command": "git status"},
                }
            )
        assert not spy.called


class TestReadMessageFileFallback:
    """_read_message_file returns None when Path.resolve() raises.

    Regression net: a permission error or symlink loop during resolve must
    fail closed (decide() returns None / allow), not crash the hook.
    """

    def test_resolve_oserror_returns_none(self, tmp_path):
        from guard.hooks.commit_message_validator import _read_message_file

        target = tmp_path / "msg.txt"
        target.write_text("body")
        with patch.object(Path, "resolve", side_effect=OSError("simulated")):
            assert _read_message_file(str(target), str(tmp_path)) is None

    def test_resolve_valueerror_returns_none(self, tmp_path):
        from guard.hooks.commit_message_validator import _read_message_file

        target = tmp_path / "msg.txt"
        target.write_text("body")
        with patch.object(Path, "resolve", side_effect=ValueError("simulated")):
            assert _read_message_file(str(target), str(tmp_path)) is None


class TestExtractAllMessagesByteCap:
    """_extract_all_messages caps scan window at 8 KiB to prevent ReDoS.

    re.DOTALL + backreference patterns can backtrack heavily on adversarial
    input. The cap keeps worst-case finite without affecting real commit
    shapes (real commit-message argv stays well under 8 KiB).
    """

    def test_input_beyond_cap_is_truncated(self):
        from guard.hooks.commit_message_validator import (
            _MESSAGE_SCAN_MAX_BYTES,
            _extract_all_messages,
        )

        # Build input where matches exist BOTH before and after the cap
        # boundary. After truncation only the pre-cap matches are extracted.
        prefix = 'git commit -m "early-msg"'
        padding_len = _MESSAGE_SCAN_MAX_BYTES - len(prefix) + 100  # past the cap
        padding = " " * padding_len
        post_cap = ' -m "post-cap-msg"'
        cmd = prefix + padding + post_cap
        messages = _extract_all_messages(cmd)
        assert "early-msg" in messages
        assert "post-cap-msg" not in messages, "post-cap match should be excluded by the 8 KiB cap"

    def test_normal_message_within_cap_works(self):
        from guard.hooks.commit_message_validator import _extract_all_messages

        messages = _extract_all_messages('git commit -m "fix bug" -m "see #123"')
        assert messages == ["fix bug", "see #123"]

    def test_oversized_input_completes_quickly(self):
        """Adversarial input completes in bounded time. Without the cap, the
        non-greedy regex on alternating quote characters could backtrack
        quadratically; with the cap, scan window is at most 8 KiB."""
        import time

        from guard.hooks.commit_message_validator import _extract_all_messages

        adversarial = "git commit " + ("-m 'x " * 5000)  # ~35 KB
        start = time.perf_counter()
        _extract_all_messages(adversarial)
        elapsed = time.perf_counter() - start
        # Real bound is microseconds. 1s is a generous CI ceiling.
        assert elapsed < 1.0, f"_extract_all_messages took {elapsed:.3f}s"
