# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TracineHQ contributors
"""Commit message validator — blocks AI attribution in git commits.

PreToolUse hook that intercepts ``git commit`` commands and rejects messages
containing AI co-author signatures, known AI tool emails, or generated-by
footers. Three layers of detection are stacked: known tool emails, attribution
trailers + tool name, and "Generated by/with" footers.
"""

from __future__ import annotations

import json
import re
import sys
from typing import Any

from guard._utils import emit_pretooluse_decision, safe_main

# Layer 1: Known AI tool emails (high confidence, zero false positives)
AI_EMAILS: list[str] = [
    r"noreply@anthropic\.com",
    r"cursoragent@cursor\.com",
    r"noreply@openai\.com",
    r"noreply@aider\.chat",
    r"bot@devin\.ai",
    r"gemini-code-assist@google\.com",
    r"\d+\+[Cc]opilot@users\.noreply\.github\.com",
    r"\d+\+github-copilot\[bot\]@users\.noreply\.github\.com",
    r"\d+\+gemini-code-assist\[bot\]@users\.noreply\.github\.com",
]

_AI_EMAIL_RE = re.compile("|".join(AI_EMAILS), re.IGNORECASE)


def check_ai_emails(message: str) -> str | None:
    """Return matched AI tool email text or ``None``."""
    m = _AI_EMAIL_RE.search(message)
    return m.group(0) if m else None


# Layer 2: Attribution trailer patterns (trailer keyword + AI tool name)
_TRAILER_KEYWORDS = r"(?:Co-[Aa]uthored-[Bb]y|Signed-off-by|Assisted-by)\s*:"

AI_TOOL_NAMES: list[str] = [
    "claude",
    "copilot",
    "cursor",
    "codex",
    "gemini",
    "aider",
    "devin",
    "cody",
    "tabnine",
    "windsurf",
    "amazon q",
    "chatgpt",
    "openai",
]

_TRAILER_RE = re.compile(
    rf"({_TRAILER_KEYWORDS})\s*(.*)",
    re.IGNORECASE | re.MULTILINE,
)

_TOOL_NAME_RE = re.compile(
    r"\b(" + "|".join(re.escape(name) for name in AI_TOOL_NAMES) + r")\b",
    re.IGNORECASE,
)


def check_ai_trailers(message: str) -> str | None:
    """Return matched trailer line containing an AI tool name, else ``None``."""
    for m in _TRAILER_RE.finditer(message):
        trailer_value = m.group(2)
        if _TOOL_NAME_RE.search(trailer_value):
            return m.group(0).strip()
    return None


# Layer 3: Generated-by footers
_GENERATED_RE = re.compile(
    r"(?:\U0001f916\s*)?Generated\s+(?:with|by)\s+"
    r"(?:Claude|Devin|AI|Copilot|Cursor|Codex|Gemini|\[Claude)",
    re.IGNORECASE,
)


def check_generated_footers(message: str) -> str | None:
    """Return matched 'Generated with/by' footer text or ``None``."""
    m = _GENERATED_RE.search(message)
    return m.group(0) if m else None


def extract_commit_message(command: str) -> str | None:
    """Extract the commit message from a ``git commit`` command string.

    Handles ``-m "msg"``, ``-m 'msg'``, ``-am "msg"``, ``--message="msg"``,
    ``--message "msg"``, and heredoc ``$(cat <<'EOF' ... EOF)`` patterns.
    Returns the message text or ``None`` if not a ``git commit -m`` form.
    """
    if not command or "git commit" not in command:
        return None

    # Heredoc pattern: -m "$(cat <<'EOF'\n...\nEOF\n)"
    heredoc_match = re.search(
        r"""-m\s+["']\$\(cat\s+<<'?EOF'?\s*\n(.*?)\nEOF\s*\)["']""",
        command,
        re.DOTALL,
    )
    if heredoc_match:
        return heredoc_match.group(1)

    long_flag_match = re.search(
        r"""--message[= ]\s*(['"])(.*?)\1""",
        command,
        re.DOTALL,
    )
    if long_flag_match:
        return long_flag_match.group(2)

    short_flag_match = re.search(
        r"""-[a-z]*m\s+(['"])(.*?)\1""",
        command,
        re.DOTALL,
    )
    if short_flag_match:
        return short_flag_match.group(2)

    return None


_BLOCK_REASON_PREFIX = (
    "Commit blocked — AI attribution detected.\n"
    "Commit as yourself. No co-author signatures, no AI tool emails, "
    "no 'Generated by' footers.\n"
)


def decide(command: str) -> dict[str, Any] | None:
    """Return a deny envelope if AI attribution is found, else ``None``."""
    message = extract_commit_message(command)
    if message is None:
        return None

    for checker in (check_ai_emails, check_ai_trailers, check_generated_footers):
        match = checker(message)
        if match:
            return emit_pretooluse_decision("deny", f"{_BLOCK_REASON_PREFIX}Found: {match}")

    return None


def hook(payload: dict[str, Any]) -> None:
    """Top-level hook entry point."""
    tool_name = payload.get("tool_name", "")
    if tool_name != "Bash":
        return

    tool_input = payload.get("tool_input", {}) or {}
    if not isinstance(tool_input, dict):
        return
    command = tool_input.get("command", "")
    if not isinstance(command, str) or "git commit" not in command:
        return

    envelope = decide(command)
    if envelope is None:
        return

    sys.stdout.write(json.dumps(envelope))
    sys.exit(2)


if __name__ == "__main__":
    safe_main(hook)
