# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TracineHQ contributors
"""Commit message validator — blocks AI attribution in git commits.

PreToolUse hook that intercepts ``git commit`` commands and rejects messages
containing AI co-author signatures, known AI tool emails, or generated-by
footers. Three layers of detection are stacked: known tool emails, attribution
trailers + tool name, and "Generated by/with" footers.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import stat
import sys
from pathlib import Path
from typing import Any

from guard._utils import _log_debug, emit_pretooluse_decision, log_decision, safe_main

_HOOK_ID = "guard.commit_message_validator"

# Cap on commit-message file reads. Real commit messages are tiny; anything
# bigger is either accidental or a soft-DoS attempt against the regex pipeline.
_FILE_MESSAGE_MAX_BYTES = 64 * 1024

# Layer 1: Known AI tool emails (high confidence, zero false positives)
AI_EMAILS: list[str] = [
    r"noreply@anthropic\.com",
    r"cursoragent@cursor\.com",
    r"noreply@openai\.com",
    r"noreply@aider\.chat",
    r"bot@devin\.ai",
    r"gemini-code-assist@google\.com",
    r"\d+\+[Cc]opilot@users\.noreply\.github\.com",
    r"\d+\+github-copilot\[bot\]@users\.noreply\.github\.com",
    r"\d+\+gemini-code-assist\[bot\]@users\.noreply\.github\.com",
]

_AI_EMAIL_RE = re.compile("|".join(AI_EMAILS), re.IGNORECASE)


def check_ai_emails(message: str) -> str | None:
    """Return matched AI tool email text or ``None``."""
    m = _AI_EMAIL_RE.search(message)
    return m.group(0) if m else None


# Layer 2: Attribution trailer patterns (trailer keyword + AI tool name)
_TRAILER_KEYWORDS = r"(?:Co-[Aa]uthored-[Bb]y|Signed-off-by|Assisted-by)\s*:"

AI_TOOL_NAMES: list[str] = [
    "claude",
    "copilot",
    "cursor",
    "codex",
    "gemini",
    "aider",
    "devin",
    "cody",
    "tabnine",
    "windsurf",
    "amazon q",
    "chatgpt",
    "openai",
    "sonnet",
    "opus",
    "haiku",
    "anthropic",
]

_TRAILER_RE = re.compile(
    rf"({_TRAILER_KEYWORDS})\s*(.*)",
    re.IGNORECASE | re.MULTILINE,
)

_TOOL_NAME_RE = re.compile(
    r"\b(" + "|".join(re.escape(name) for name in AI_TOOL_NAMES) + r")\b",
    re.IGNORECASE,
)


def check_ai_trailers(message: str) -> str | None:
    """Return matched trailer line containing an AI tool name, else ``None``."""
    for m in _TRAILER_RE.finditer(message):
        trailer_value = m.group(2)
        if _TOOL_NAME_RE.search(trailer_value):
            return m.group(0).strip()
    return None


# Layer 3: Generated-by footers. Accept whitespace, hyphen, or trailing colon
# between "Generated", "by"/"with", and the tool name (``Generated-by: Claude``
# slips past whitespace-only matchers).
_GENERATED_RE = re.compile(
    r"(?:\U0001f916\s*)?Generated[\s\-]+(?:with|by)[\s\-:]+"
    r"(?:Claude|Devin|AI|Copilot|Cursor|Codex|Gemini|Sonnet|Opus|Haiku|\[Claude)",
    re.IGNORECASE,
)


def check_generated_footers(message: str) -> str | None:
    """Return matched 'Generated with/by' footer text or ``None``."""
    m = _GENERATED_RE.search(message)
    return m.group(0) if m else None


# Sentinel returned by ``_read_message_file`` when the path resolves to a
# stream / non-regular file — the caller must deny rather than treat as
# "no message".
STREAM_FILE_SENTINEL = "\x00guard:stream-file\x00"

# Path forms that always indicate an attacker-controlled stream input git
# would read at runtime — the validator cannot pre-read these reliably.
_STREAM_LITERAL_PATHS: frozenset[str] = frozenset({"/dev/stdin", "/dev/null", "/dev/fd/0", "-"})
_STREAM_PATH_PREFIXES: tuple[str, ...] = ("/dev/fd/", "/proc/self/fd/")


def _looks_like_stream_path(path: str) -> bool:
    """Return True for stdin / fd / fifo / chardev paths."""
    if path in _STREAM_LITERAL_PATHS:
        return True
    if path.startswith(_STREAM_PATH_PREFIXES):
        return True
    try:
        real = os.path.realpath(path)
    except (OSError, ValueError):
        return False
    if real in _STREAM_LITERAL_PATHS or real.startswith(_STREAM_PATH_PREFIXES):
        return True
    try:
        st = os.stat(real)  # noqa: PTH116 -- stat for st_mode classification
    except OSError:
        return False
    mode = st.st_mode
    return bool(stat.S_ISCHR(mode) or stat.S_ISFIFO(mode) or stat.S_ISBLK(mode))


def _read_message_file(path: str, cwd: str | None) -> str | None:
    """Read a commit-message file safely, returning its text or ``None``.

    Resolves ``~`` and, for relative paths, joins against ``cwd`` (the hook
    payload's reported working directory). Caps reads at
    ``_FILE_MESSAGE_MAX_BYTES`` so an attacker-supplied huge file cannot
    soft-DoS the regex pipeline. Any I/O failure returns ``None`` — git will
    surface the underlying error to the user when the commit runs.

    If the path is a stream / FIFO / character device / fd, returns the
    sentinel ``STREAM_FILE_SENTINEL`` so the caller can deny with a clear
    message rather than silently passing through.
    """
    if not path:
        return None
    if _looks_like_stream_path(path):
        return STREAM_FILE_SENTINEL
    p = Path(path).expanduser()
    if not p.is_absolute() and cwd:
        p = Path(cwd) / p
    if _looks_like_stream_path(str(p)):
        return STREAM_FILE_SENTINEL
    try:
        with p.open("rb") as fh:
            raw = fh.read(_FILE_MESSAGE_MAX_BYTES + 1)
    except OSError as exc:
        _log_debug(f"commit_message_validator: cannot read {path!r}: {exc}")
        return None
    if len(raw) > _FILE_MESSAGE_MAX_BYTES:
        _log_debug(
            f"commit_message_validator: {path!r} exceeds {_FILE_MESSAGE_MAX_BYTES} bytes; ignoring"
        )
        return None
    return raw.decode("utf-8", errors="replace")


def _extract_file_flag_path(command: str) -> str | None:  # noqa: PLR0911 -- linear flag-form dispatch; each early-return matches one git -F syntax
    """Return the path argument to ``-F`` / ``--file=`` / ``-F=`` / ``-F-``.

    Tokenizes via ``shlex`` so quoted paths and embedded spaces are handled.
    Falls back to ``None`` if the command can't be parsed (unbalanced quotes
    etc.) — the caller treats that as "no file flag," and the eventual
    ``git commit`` will fail on its own terms.
    """
    try:
        tokens = shlex.split(command, posix=True)
    except ValueError:
        return None
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok in ("-F", "--file"):
            if i + 1 < len(tokens):
                return tokens[i + 1]
            return None
        if tok == "-F-":
            return "-"
        if tok.startswith("--file="):
            return tok[len("--file=") :]
        if tok.startswith("-F="):
            return tok[len("-F=") :]
        i += 1
    return None


def _extract_all_messages(command: str) -> list[str]:
    """Return every ``-m`` / ``--message`` payload in ``command``.

    Multi-``-m`` is the bypass shape: ``git commit -m "fix" -m "Co-Authored-By: ..."``
    where a naive ``re.search`` returns only the first hit and the second
    message escapes the AI-attribution detector. We run ``re.findall`` over
    both the long and short flag forms and return them in order.
    """
    messages: list[str] = [
        m.group(2) for m in re.finditer(r"""--message[= ]\s*(['"])(.*?)\1""", command, re.DOTALL)
    ]
    messages.extend(
        m.group(2) for m in re.finditer(r"""(?<!-)-[a-z]*m\s+(['"])(.*?)\1""", command, re.DOTALL)
    )
    return messages


def extract_commit_message(command: str, cwd: str | None = None) -> str | None:
    """Extract the commit message from a ``git commit`` command string.

    Handles ``-m "msg"``, ``-m 'msg'``, ``-am "msg"``, ``--message="msg"``,
    ``--message "msg"``, multiple repeated ``-m`` / ``--message`` flags,
    heredoc ``$(cat <<'EOF' ... EOF)``, and
    ``-F <path>`` / ``--file=<path>`` / ``-F-`` (file-backed messages).

    Multiple ``-m`` payloads are concatenated with blank-line separators —
    the format git itself produces — so AI-attribution detectors run against
    the joined text.

    For file-backed messages, the file is read from ``cwd`` (or absolute /
    home-relative paths) and capped at ``_FILE_MESSAGE_MAX_BYTES``. If the
    target is a stream / FIFO / character device, returns the
    ``STREAM_FILE_SENTINEL`` so the caller can deny.

    Returns the message text or ``None`` if the command isn't a recognized
    message-bearing ``git commit`` form (or the file can't be read).
    """
    if not command or "git commit" not in command:
        return None

    # Heredoc pattern: -m "$(cat <<'EOF'\n...\nEOF\n)"
    heredoc_match = re.search(
        r"""-m\s+["']\$\(cat\s+<<'?EOF'?\s*\n(.*?)\nEOF\s*\)["']""",
        command,
        re.DOTALL,
    )
    if heredoc_match:
        return heredoc_match.group(1)

    messages = _extract_all_messages(command)
    if messages:
        return "\n\n".join(messages)

    file_path = _extract_file_flag_path(command)
    if file_path is not None:
        return _read_message_file(file_path, cwd)

    return None


_BLOCK_REASON_PREFIX = (
    "Commit blocked — AI attribution detected.\n"
    "Commit as yourself. No co-author signatures, no AI tool emails, "
    "no 'Generated by' footers.\n"
)


_STREAM_DENY_REASON = (
    "Commit message comes from a stream / non-file source (stdin, /dev/null, "
    "/proc/self/fd/*, FIFO, character device) that this validator cannot "
    "pre-read. Write the message to a regular file first, then commit with "
    "`git commit -F <path>`."
)

_OPAQUE_SOURCE_DENY_REASON = (
    "Commit message uses a shell shape this validator cannot inspect: "
    "ANSI-C ``$'...'`` quoting, ``$VAR`` / ``${VAR}`` expansion, or process "
    "substitution ``-F <(...)`` / ``-F <(echo ...)``. The shell expands these "
    "after the hook runs, so attribution markers can be smuggled past the "
    "AI-tool checks. Write the message inline as a literal ``-m '...'`` or "
    "via ``git commit -F <path>`` pointing at a regular file."
)

# ``-m $'...'``, ``--message=$'...'`` ANSI-C quoting; ``$VAR`` / ``${VAR}``
# variable expansion in the message slot; ``-F <(...)`` process substitution.
_OPAQUE_MESSAGE_RE = re.compile(
    r"""(?:-m|--message[= ])\s*(?:\$'|"\s*\$[A-Za-z_{]|'\s*\$[A-Za-z_{])"""
    r"""|(?:-m|--message[= ])\s*\$\{?[A-Za-z_]"""
    r"""|(?:-F|--file)[= ]\s*<\("""
)


def _has_opaque_message_source(command: str) -> bool:
    """Return True for commit shapes whose message body the hook can't read."""
    return bool(_OPAQUE_MESSAGE_RE.search(command))


def decide(command: str, cwd: str | None = None) -> dict[str, Any] | None:
    """Return a deny envelope if AI attribution is found, else ``None``."""
    if _has_opaque_message_source(command):
        return emit_pretooluse_decision("deny", _OPAQUE_SOURCE_DENY_REASON)

    message = extract_commit_message(command, cwd=cwd)
    if message is None:
        return None

    if message is STREAM_FILE_SENTINEL or message == STREAM_FILE_SENTINEL:
        return emit_pretooluse_decision("deny", _STREAM_DENY_REASON)

    for checker in (check_ai_emails, check_ai_trailers, check_generated_footers):
        match = checker(message)
        if match:
            return emit_pretooluse_decision("deny", f"{_BLOCK_REASON_PREFIX}Found: {match}")

    return None


def hook(payload: dict[str, Any]) -> None:
    """Top-level hook entry point."""
    tool_name = payload.get("tool_name", "")
    if tool_name != "Bash":
        return

    tool_input = payload.get("tool_input", {}) or {}
    if not isinstance(tool_input, dict):
        return
    command = tool_input.get("command", "")
    if not isinstance(command, str) or "git commit" not in command:
        return

    cwd = payload.get("cwd")
    cwd_str = cwd if isinstance(cwd, str) else None
    envelope = decide(command, cwd=cwd_str)
    if envelope is None:
        return

    hso = envelope.get("hookSpecificOutput", {})
    log_decision(
        hook_id=_HOOK_ID,
        event="PreToolUse",
        tool_name="Bash",
        decision="deny",
        reason=hso.get("permissionDecisionReason", ""),
        command_excerpt=command,
        session_id=str(payload.get("session_id", "")),
        cwd=cwd_str,
    )
    sys.stdout.write(json.dumps(envelope))
    sys.exit(2)


if __name__ == "__main__":
    safe_main(hook)
